// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwahh04uu9vHWYY6oVY9wMEkwvTqqTWVY',
    appId: '1:1078635706977:web:d24bee3befa627836e4820',
    messagingSenderId: '1078635706977',
    projectId: 'afgasgb',
    authDomain: 'afgasgb.firebaseapp.com',
    storageBucket: 'afgasgb.appspot.com',
    measurementId: 'G-4PGC1S92K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKiHsBO-AAX90s_NgwScgzp54QyrAvZ74',
    appId: '1:1078635706977:android:66fe8079e55cdb646e4820',
    messagingSenderId: '1078635706977',
    projectId: 'afgasgb',
    storageBucket: 'afgasgb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCoLzPgf21IehUfIzN8am_vTCO8uRmv40',
    appId: '1:1078635706977:ios:daf2f547c9f69f846e4820',
    messagingSenderId: '1078635706977',
    projectId: 'afgasgb',
    storageBucket: 'afgasgb.appspot.com',
    iosBundleId: 'com.example.goldenHouseFlutterFinalApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCoLzPgf21IehUfIzN8am_vTCO8uRmv40',
    appId: '1:1078635706977:ios:80bbf5e0d2cb0a216e4820',
    messagingSenderId: '1078635706977',
    projectId: 'afgasgb',
    storageBucket: 'afgasgb.appspot.com',
    iosBundleId: 'com.example.goldenHouseFlutterFinalApplication.RunnerTests',
  );
}
